name: Publish to Production
on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build with Docker
        run: |
          docker compose -f docker-compose-build.yml run landing npm install
          docker compose -f docker-compose-build.yml run landing npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: rfrns-landing
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: stable
